### ISSUE TITLE
Documentation 'Translating Menu Accelerators' is outdated (for master)

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#24323]
The documentation states:

https://github.com/wxWidgets/wxWidgets/blob/47b011c665b7e07eef90489c22ff426a60b38ddb/docs/doxygen/overviews/internationalization.h#L114-L118

But with the current master it is no longer sufficient to only provide translations of "ctrl", "alt" and "shift".

Since 4dcda62f9d9789519b6dd7629a8a256641dc56ad (Normalize displayed accelerators in wxMSW too, 2022-12-09) it is also necessary to provide translations of "Ctrl+", "Alt+" and "Shift+".
Otherwise, with wxMSW, the modifier keys will be displayed normalized in English.

### Platform and version information

- wxWidgets version  you use: master (47b011c665b7e07eef90489c22ff426a60b38ddb)
- wxWidgets port  you use: wxMSW
- OS  and its version: Windows 10

**Comment by vadz** [comment]
I'm not sure if we did this intentionally, i.e. can "Ctrl+" be actually translated to something different from the translation of "Ctrl" followed by "+" in any language?

**Comment by taler21** [comment]
Parsing the accelerator string is done with hardcoded '+' and '-'.

https://github.com/wxWidgets/wxWidgets/blob/47b011c665b7e07eef90489c22ff426a60b38ddb/src/common/accelcmn.cpp#L181-L191

**Comment by vadz** [comment]
In principle, translations could map everything to `Accel-Letter` if the target language preferred this convention to using `+`. I have no idea if this really exists though.

**Comment by taler21** [comment]
You mean translating '+' separately in a context called `Accel-Letter`?

I took a look to the existing wxWidgets catalogs.
* In principle, all existing translations use the letter '+'.
* Slovenian is the only exception where '-' is used in its translations.
  But I think '+' would also be correct here, as on Windows 10 with Slovenian selected as the display language, '+' is used in accelerators of the text editor.
  By the way, the translations of the modifiers are probably also wrong, since the Slovenian text editor of Windows uses "Alt", "Ctrl", "Shift" and not "Izmenjalka", "Krmilka", "Dvigalka".
* Of course there are a few catalogs that do not contain a translation of "Ctrl+", "Alt+" or "Shift+".
  These catalogs are: el, fa_IR, fi, hi, ko_KR, ms, nb

In any case there will be an incompatibility from wxWidgets 3.2 to 3.3.
* In wxWidgets-3.2 you need to provide translations of the modifiers from their lower case names (ctrl, alt, shift).
* In wxWidgets-3.3 you will need to provide translations of the modifiers in the notation they are displayed (Ctrl, Alt, Shift).
  _Or with the current master, translations of their lower case names and additionally those of "Ctrl+", "Alt+" and "Shift+"._

Sure, not everyone will be affected by this incompatibility.
Those using English texts in their source code and loading the standard wxWidgets catalogs will not be affected.
But those who use non-English texts in their source code and/or do not load the standard wxWidgets catalogs are affected and will need to adapt their provided translations.

**Comment by vadz** [comment]
Thanks for checking this. If there are no languages that need to translate `Ctrl+` to `Ctrl-`, then I agree that it would be better to revert to 3.2 behaviour and just translate the modifiers separately.

I'm not sure what would be the minimal change required to do it, but if you do, please let me know and/or just make the PR with it directly. TIA!

**Comment by taler21** [comment]
Sorry, but I don't understand how "RawCtrl" is supposed to work.

The documentation states:

https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/interface/wx/menuitem.h#L458-L463

1. When parsing, "Ctrl" and "RawCtrl" are treated as different keys on each platform.
   https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/src/common/accelcmn.cpp#L192-L193
   But in `wxAcceleratorEntry::ToString()` "RawCtrl+" is only translated for `__WXMAC__`.
   https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/src/common/accelcmn.cpp#L348-L351
2. How should translators translate the lower case name of the modifier "rawctrl"?
   Should it even be translated?
3. How should translators translate this modifier in the notation that is displayed ("RawCtrl+")?
   Should it be the same translation as of "Ctrl+"?
4. If so, wouldn't it be better to map "RawCtrl+" to "Ctrl+" and only translate the latter?
5. And how else would "RawCtrl+" be translated in English to "Ctrl+", without a standard English wxWidgets catalog?

**Comment by taler21** [comment]
Another aspect of using `wxAcceleratorEntry::ToString()` to display normalized accelerators in the menu is that the modifiers are not in the usual order.

https://github.com/wxWidgets/wxWidgets/blob/f24b3d54833a1c15ae3bba87dead83bf9a90c41d/src/common/accelcmn.cpp#L342-L351

The usual order of modifiers under MSW is `[Ctrl+][Shift+][Alt+]`, but definitely not `[Alt+]` in the first place.

Don't know if this can be easily changed since this code is also called by `wxAcceleratorEntry::ToRawString()` to generate a textual representation of the accelerator for saving in configuration files.
Maybe yes, since such loaded text is probably parsed again by `wxAcceleratorEntry::FromString()` anyway and the order of the modifiers doesn't matter there.

**Comment by taler21** [comment]
You are right, the German translation is incorrect.
It should be as follows, and in my opinion also be corrected in 3.2.

```patch
diff --git "a/samples/internat/de/internat.po" "b/samples/internat/de/internat.po"
index 53e61c5582..7cc61ae692 100644
--- "a/samples/internat/de/internat.po"
+++ "b/samples/internat/de/internat.po"
@@ -39,7 +39,7 @@ msgstr "Internationale wxWidgets-Anwendung"
 
 #: internat.cpp:295
 msgid "&Test locale availability...\tCtrl-T"
-msgstr "&Teste Gebietsschemaverfügbarkeit...\tCtrl-T"
+msgstr "&Teste Gebietsschemaverfügbarkeit...\tStrg-T"
 
 #: internat.cpp:300
 msgid "E&xit"

```

As far as I know, wxGTK behaves differently than wxMSW in this regard.
In wxGTK, how modifiers are displayed depends on the system language.
When catalogs are loaded via `wxTranslations` in a language other than the system language, the modifiers are not displayed as translated in the catalogs, but according to the system language.

Unfortunately, loading catalogs in any language can no longer be tested in the internat sample since eb5bffd3caee3225f64bef56bb6b6e8147e81887 (`Stop allowing to select the language in the internat sample, 2021-08-14`).

**Comment by taler21** [comment]
Here is a patch for the internat sample to demonstrate both issues mentioned so far in this ticket, that were introduced in master as side effects of 4dcda62f9d9789519b6dd7629a8a256641dc56ad (`Normalize displayed accelerators in wxMSW too, 2022-12-09`).
The first issue was mentioned in the [initial comment](https://github.com/wxWidgets/wxWidgets/issues/24323#issue-2135868355), the second in a [later comment](https://github.com/wxWidgets/wxWidgets/issues/24323#issuecomment-1954348935).

<details>
<summary>Patch for internat sample</summary>
 
```patch
diff -r -u -p a/samples/internat/de/internat.po b/samples/internat/de/internat.po
--- a/samples/internat/de/internat.po	2025-01-31 08:30:51.622653700 +0100
+++ b/samples/internat/de/internat.po	2025-01-31 08:38:20.687766200 +0100
@@ -33,6 +33,21 @@ msgstr "Setze das Gebietsschema beim Sta
 msgid "Couldn't find/load 'internat' catalog for %s."
 msgstr "Konnte den 'internat'-Katalog für %s nicht finden/laden."
 
+#: internat.cpp:272
+msgctxt "keyboard key"
+msgid "ctrl"
+msgstr "Strg"
+
+#: internat.cpp:273
+msgctxt "keyboard key"
+msgid "shift"
+msgstr "Umschalt"
+
+#: internat.cpp:274
+msgctxt "keyboard key"
+msgid "alt"
+msgstr "Alt"
+
 #: internat.cpp:289
 msgid "International wxWidgets App"
 msgstr "Internationale wxWidgets-Anwendung"
@@ -41,6 +56,10 @@ msgstr "Internationale wxWidgets-Anwendu
 msgid "&Test locale availability...\tCtrl-T"
 msgstr "&Teste Gebietsschemaverfügbarkeit...\tStrg-T"
 
+#: internat.cpp:313
+msgid "Keyboard shortcut...\tCtrl+Shift+Alt+B"
+msgstr "Tastenkombination...\tStrg+Umschalt+Alt+B"
+
 #: internat.cpp:300
 msgid "E&xit"
 msgstr "&Schließen"
diff -r -u -p a/samples/internat/internat.cpp b/samples/internat/internat.cpp
--- a/samples/internat/internat.cpp	2025-01-31 08:30:51.247674900 +0100
+++ b/samples/internat/internat.cpp	2025-01-31 08:38:20.536572000 +0100
@@ -58,7 +58,7 @@
 class MyApp: public wxApp
 {
 public:
-    MyApp() { m_setLocale = Locale_Ask; }
+    MyApp() { m_setLocale = Locale_Set; }
 
     virtual void OnInitCmdLine(wxCmdLineParser& parser) override;
     virtual bool OnCmdLineParsed(wxCmdLineParser& parser) override;
@@ -110,6 +110,7 @@ enum
 {
     INTERNAT_TEST = wxID_HIGHEST,
     INTERNAT_PLAY,
+    INTERNAT_TEST_ACCEL,
     INTERNAT_TEST_1,
     INTERNAT_TEST_2,
     INTERNAT_TEST_3,
@@ -132,6 +133,7 @@ enum
 wxBEGIN_EVENT_TABLE(MyFrame, wxFrame)
     EVT_MENU(INTERNAT_TEST, MyFrame::OnTestLocaleAvail)
     EVT_MENU(wxID_ABOUT, MyFrame::OnAbout)
+    EVT_MENU(INTERNAT_TEST_ACCEL, MyFrame::OnAbout)
 #ifdef USE_COREUTILS_MO
     EVT_MENU(wxID_HELP, MyFrame::OnCoreutilsHelp)
 #endif // USE_COREUTILS_MO
@@ -246,6 +248,8 @@ bool MyApp::OnInit()
         wxTranslations* const trans = new wxTranslations();
         wxTranslations::Set(trans);
 
+        trans->SetLanguage( wxLANGUAGE_GERMAN );
+
         // Initialize the catalogs we'll be using.
         if ( !trans->AddCatalog("internat") )
         {
@@ -258,6 +262,18 @@ bool MyApp::OnInit()
         trans->AddCatalog("wxstd");
             // NOTE: it's not an error if we couldn't find it!
 
+        // In case the wxWidgets standard catalog 'wxstd' is not present, we
+        // need to provide translations of the accelerator modifiers from
+        // their lower case names (ctrl, alt, shift) in our sample catalog.
+        // As stated in the documentation, those are required for accelerators
+        // with translated modifier names to work correctly.
+        const char* modifiers[] =
+        {
+            wxGETTEXT_IN_CONTEXT("keyboard key", "ctrl"),
+            wxGETTEXT_IN_CONTEXT("keyboard key", "shift"),
+            wxGETTEXT_IN_CONTEXT("keyboard key", "alt")
+        };
+
         // this catalog is installed in standard location on Linux systems and
         // shows that you may make use of the standard message catalogs as well
         //
@@ -294,6 +310,8 @@ MyFrame::MyFrame()
     file_menu->Append(INTERNAT_TEST, _("&Test locale availability...\tCtrl-T"));
     file_menu->AppendSeparator();
 
+    file_menu->Append(INTERNAT_TEST_ACCEL, _("Keyboard shortcut...\tCtrl+Shift+Alt+B"));
+
     // since wxID_EXIT is a stock ID it will automatically get a translated help
     // string; nice isn't it?
     file_menu->Append(wxID_EXIT, _("E&xit"));

```
</details>

### To Reproduce

1. **IMPORTANT:** Recreate the German `internat.mo` file after the `internat.po` file has been changed by the patch.
2. Start the internat sample.

With wxWidgets 3.2.6, the accelerator keys are displayed correctly, i.e. translated and in the usual order.

![Image](https://github.com/user-attachments/assets/fe3c3efb-25a1-42cb-9242-a0b2785b92ca)

But with the current master they are neither translated nor in the usual order.

![Image](https://github.com/user-attachments/assets/9751e609-49ad-40bc-89a3-ece1c824dc46)

**Comment by vadz** [comment]
Sorry for returning to this so late, but I'm still not sure what should be done here.

If we revert 4dcda62f (Normalize displayed accelerators in wxMSW too, 2022-12-09) and fix this in some other way, e.g. by just replacing all occurrences of "RawCtrl" after TAB with "Ctrl", would this fix all the problems? If so, I think we should do this (instead of applying #25130 which codifies the current behaviour that seems wrong).

**Comment by taler21** [comment]
PR #25130 does not address anything of this ticket, it is completely unrelated to it.
It adapts the documentation to a completely different, much older change (one introduced in version 3.1.7).

**Comment by vadz** [comment]
Sorry for mixing this up.

Thinking more about this, I believe the right thing to do would be to normalize the accelerators, but translate each of them separately when doing it. This would, however, require having translations for "Ctrl" etc and not just "ctrl"... But then I have no idea why do we use lower case names in `wxAcceleratorEntry::ParseAccel()` when they're compared case-insensitively anyhow, we could just as well use capitalized names for them. What a mess :-(

**Comment by vadz** [comment]
I think I've addressed all the problems discussed here in #25225, it would be great if you could please test it and let me know if you still see anything wrong. TIA!

**Comment by vadz** [comment]
> The usual order of modifiers under MSW is `[Ctrl+][Shift+][Alt+]`, but definitely not `[Alt+]` in the first place.

Sorry, forgot to say that I didn't change this because I'm not sure if we really should be doing this in common code, i.e. if the other platforms use the same convention. The only application using accelerators with `Alt` and something else I could find on my system was VS Code (which is Electron-based and so is probably not a good example, but I don't have any others) and it does use the same order as we do now. So perhaps we need to do this in a platform-specific way?

Anyhow, I don't think this issue is very important because such accelerators seem/should be relatively rare, but please open another issue about this if you think it merits it.

**Comment by taler21** [comment]
Works as you described. Thanks for working on these improvements!

Since it is an incompatible change in 3.3.0, this should probably be noted in "Changes in behaviour not resulting in compilation errors".
Most people will not be affected, but there will be some, like us, who do not load the standard catalogs or provide missing translations themselves.
They will need to adapt their provided translations when upgrading to wxWidgets 3.3.0.

The fact that the modifiers are no longer displayed in the usual order under MSW is, in my opinion, an unsightly regression that should be fixed.
I don't agree that accelerators with `Alt` are rare. I am convinced that most extensive applications have some, including ours (which is why I noticed the change).

Visual Studio is the best example to see what order should be used in wxMSW (`[Ctrl+][Shift+][Alt+]`).

GIMP can be used to see what order should be used in wxGTK (`[Shift+][Ctrl+][Alt+]`).
By the way, in wxGTK it is already done in a platform-specific way, and therefore the order already matches that of GIMP.

**Comment by vadz** [comment]
> Works as you described. Thanks for working on these improvements!

Thanks for testing!
 
> Since it is an incompatible change in 3.3.0, this should probably be noted in "Changes in behaviour not resulting in compilation errors". Most people will not be affected, but there will be some, like us, who do not load the standard catalogs or provide missing translations themselves. They will need to adapt their provided translations when upgrading to wxWidgets 3.3.0.

I thought about documenting it there but then I realized that I didn't really know what to document — because this change only affects translations of strings in wx itself, normally it should have no effect on the applications. I didn't think about your use case in which you provide replacements for the wx translations (if I understand correctly?), but I think this should be very, very rare, and trying to explain this in a succinct form in the change log was too difficult for me to do. But if you can propose a short paragraph (2-3 75 character lines) that can be used to describe this change, I'd be glad to include it.

> The fact that the modifiers are no longer displayed in the usual order under MSW is, in my opinion, an unsightly regression that should be fixed. I don't agree that accelerators with `Alt` are rare. I am convinced that most extensive applications have some, including ours (which is why I noticed the change).

Just to be clear, I think accelerators using `Alt` are very common, but accelerators using `Alt` and some other modifier(s) are IMHO relatively rare. 

> Visual Studio is the best example to see what order should be used in wxMSW (`[Ctrl+][Shift+][Alt+]`).
> 
> GIMP can be used to see what order should be used in wxGTK (`[Shift+][Ctrl+][Alt+]`). By the way, in wxGTK it is already done in a platform-specific way, and therefore the order already matches that of GIMP.

Yes, it's nice that wxGTK lets GTK do it, but it's still not great to encode MSW-specific order in the common code, even if it ends up not being used by wxGTK. But unfortunately doing it in a platform-specific way risks being difficult too... I've added 654ad9e4238b372fe49019068531260560f08f44 changing the order to MSW one to the PR for now, but this is rather unsatisfactory.
