### ISSUE TITLE
wxListCtrl does not react to on-the-fly dark-mode vs light-mode switches

### ISSUE THREAD

**Issue by bk138** [wxWidgets/wxWidgets#25007]
### Description

wxListCtrl from wxWidgets v3.2.6 does not react to on-the-fly dark-mode vs light-mode switches

#### Bug description:

wxListCtrl on GTK retains the original fore- and background colours on switching between light and dark mode while the application is running. When the application is restarted, the colours are OK, i.e. in line with other widgets.

#### Expected vs observed behaviour:

Some screenshots of https://github.com/wxWidgets/wxWidgets/tree/master/samples/listctrl showing the issue:

##### app started in light mode, good
![grafik](https://github.com/user-attachments/assets/6930243c-bea0-43ad-bffc-a07a56da10ec)

##### switched to dark mode while app is running, bad
![grafik](https://github.com/user-attachments/assets/0de1edf1-3227-42fd-879e-102647977eed)

##### app started in dark mode, good
![grafik](https://github.com/user-attachments/assets/fcf33ffd-c581-428f-b52e-369fbefe802a)

#### Stack trace:

N/A

#### Patch or snippet allowing to reproduce the problem:

https://github.com/wxWidgets/wxWidgets/tree/master/samples/listctrl shows the behaviour.

#### To Reproduce:

See above. FYI I also checked listrctrl example on MacOS, issue is _not_ present there so seems to be GTK-specific.

### Platform and version information

- wxWidgets version  you use: 3.2.6
- wxWidgets port  you use: wxGTK
- OS  and its version: Debian 12
  
  + GTK version:   3.24.38
  + Which GDK  backend is used: happens with both, checked this
  + Desktop environment : Gnome
  + Current theme:  Adwaita

**Comment by stevecor** [comment]
This is fixed by f12b247d26b6a1f2d48e88f2892c51988acbb578.

**Comment by PBfordev** [comment]
I am not saying this is not fixed (I am not using Linux) but certainly this could not be fixed by https://github.com/wxWidgets/wxWidgets/commit/f12b247d26b6a1f2d48e88f2892c51988acbb578.

This ticket is about GTK (generic listctrl) and wxWidgets 3.2, the referenced commit is MSW-only in the 3.3 branch.

**Comment by bk138** [comment]
I can have a look the next days.

**Comment by bk138** [comment]
Confirming this is fixed at the state of 3df55053824b8ab2199cecea0e920df294c13547 i.e. currrent master as of writing.
